export const ANDROID_FLOATING_TAB_BAR_COMPACT_HEIGHT_THRESHOLD = 430;
export const ANDROID_FLOATING_TAB_BAR_REGULAR_HEIGHT = 68;
export const ANDROID_FLOATING_TAB_BAR_COMPACT_HEIGHT = 60;
export const ANDROID_FLOATING_TAB_BAR_REGULAR_BOTTOM_OFFSET = 18;
export const ANDROID_FLOATING_TAB_BAR_COMPACT_BOTTOM_OFFSET = 12;
export const ANDROID_FLOATING_TAB_BAR_HORIZONTAL_MARGIN = 12;
export const ANDROID_FLOATING_TAB_BAR_MAX_WIDTH = 520;
export const ANDROID_FLOATING_TAB_BAR_CONTENT_GAP = 12;
